### ISSUE TITLE
README unclear on what to update in secrets file

### ISSUE THREAD

**Issue by eolszewski** [transmute-industries/transmute-dapp#4]
All it says is "Update environment.secret.env" - with what?

I assume all I need to do is update my project name and this should be fine?

**Comment by OR13** [comment]
This is kinda sad... those values are not really secrets anyway. Really this is placeholder for some secret management system we have yet to define or implement.

**Comment by eolszewski** [comment]
We discussed leveraging keychain values for this which seems reasonable?

**Comment by eolszewski** [comment]
https://github.com/transmute-industries/transmute-cli/commit/77da4566934c75270be436a9fcb7717269513f2c
