### ISSUE TITLE
firebase-client-config.json unused

### ISSUE THREAD

**Issue by eolszewski** [transmute-industries/transmute-dapp#5]
This should be imported into environment.web.js as such
`firebaseApp: firebase.initializeApp(require('./firebase-client-config.json'))`

**Comment by OR13** [comment]
initializing firebaseApp inside of the config can cause portability issues.

The direction we are headed, we want the configs to hold only values, and not require anything.

The consumer of the config will have to require and wire things up, but at least what they are using will be portable... this solution is not (requires a bundler).
