### ISSUE TITLE
[warning] No ./functions/.transmute/environment.web was detected.

### ISSUE THREAD

**Issue by eolszewski** [transmute-industries/transmute-dapp#7]
Running docker-compose up renders this error.

**Comment by eolszewski** [comment]
This was caused by using the Dockerfile.serve instead of Dockerfile in the functions directory.

Why do we have a Dockerfile.serve?

**Comment by OR13** [comment]
When working with docker, its desirable to have some files which just build an image... and other which build and run... usually they are mostly the same. This warning is saying that your functions have not been configured correctly, and `transmute serve` will try and use top level configs `~/.transmute`, inside a docker container... that will be a problem. outside it should be fine.

this is why when testing functions in docker, we need 

```
 volumes:
     - ./functions/.transmute:/usr/src/app/functions/.transmute
```

If `./functions/.transmute` is correct, you will not see this error inside a container.

**Comment by eolszewski** [comment]
https://github.com/transmute-industries/transmute-cli/issues/7
