### ISSUE TITLE
Running without docker locally causes some styles to go missing?

### ISSUE THREAD

**Issue by eolszewski** [transmute-industries/transmute-dapp#8]
<img width="1011" alt="screen shot 2017-11-10 at 11 25 15 am" src="https://user-images.githubusercontent.com/3613197/32670623-f543b4c2-c609-11e7-95a0-97dbd05ed6da.png">

**Comment by OR13** [comment]
Semantic is not included.

Advanced setup requires some instructions for using semantic such as:

```
cd semantic
gulp watch
gulp build
```

**Comment by eolszewski** [comment]
Can this be included in the README?

**Comment by OR13** [comment]
This error is caused by git ignore, build folder required by semantic is excluded

**Comment by OR13** [comment]
semantic/tasks/build was being excluded. This impacts both advanced and basic/master

**Comment by OR13** [comment]
Done, see advanced branch.
